[package]
name = "ason"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.35"
hexfloat2 = "0.1.3"

[dev-dependencies]
pretty_assertions = "1.4.0"
